# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-18.04"

  config.vm.define "lamp-vm1" do |machine|
    machine.ssh.insert_key = false
    machine.vm.network "private_network", ip: "192.168.255.101"
    machine.ssh.private_key_path = [".ssh/vagrant_rsa", "~/.vagrant.d/insecure_private_key"]
    machine.vm.provision "file", source: ".ssh/vagrant_rsa.pub", destination: "~/.ssh/authorized_keys"
    machine.vm.provider "virtualbox" do |vb|
      vb.memory = 768
    end
  end

  config.vm.define "lamp-vm2" do |machine|
    machine.ssh.insert_key = false
    machine.vm.network "private_network", ip: "192.168.255.102"
    machine.ssh.private_key_path = [".ssh/vagrant_rsa", "~/.vagrant.d/insecure_private_key"]
    machine.vm.provision "file", source: ".ssh/vagrant_rsa.pub", destination: "~/.ssh/authorized_keys"
    machine.vm.provider "virtualbox" do |vb|
      vb.memory = 768
    end
  end

  config.vm.define "haproxy-vm" do |machine|
    machine.ssh.insert_key = false
    machine.vm.network "private_network", ip: "192.168.255.103"
    machine.ssh.private_key_path = [".ssh/vagrant_rsa", "~/.vagrant.d/insecure_private_key"]
    machine.vm.provision "file", source: ".ssh/vagrant_rsa.pub", destination: "~/.ssh/authorized_keys"
    machine.vm.provider "virtualbox" do |vb|
      vb.memory = 768
    end
  end
end
