---
- name: Add repository for php 7.3
  apt_repository: 
    repo: 'ppa:ondrej/php'

- name: Install dependencies for php 7.3
  apt:
    name: software-properties-common
    state: present
    update_cache: yes
    cache_valid_time: 86400

- name: Install php 7.3 with common extensions
  apt:
    name: php7.3
    state: present
  # with_items:
  #   - libapache2-mod-php7.3
  #   - php7.3-common
  #   - php7.3-mysql
  #   - php7.3-xml
  #   - php7.3-xmlrpc
  #   - php7.3-curl
  #   - php7.3-gd
  #   - php7.3-imagick
  #   - php7.3-cli
  #   - php7.3-dev
  #   - php7.3-imap
  #   - php7.3-mbstring
  #   - php7.3-opcache
  #   - php7.3-soap
  #   - php7.3-zip
  #   - php7.3-intl

- name: Install common extensions for php 7.3
  apt:
    pkg:
      - libapache2-mod-php7.3
      - php7.3-common
      - php7.3-mysql
      - php7.3-xml
      - php7.3-xmlrpc
      - php7.3-curl
      - php7.3-gd
      - php7.3-imagick
      - php7.3-cli
      - php7.3-dev
      - php7.3-imap
      - php7.3-mbstring
      - php7.3-opcache
      - php7.3-soap
      - php7.3-zip
      - php7.3-intl