---
- name: Perform aws instance server setup
  hosts: all
  become: yes

  vars:
    host: 192.168.255.101
    user: vagrant
    ssh_key_path: ../vagrant/.ssh/vagrant_rsa

  roles:
    - apache
    - php
    - mysql
    - wordpress
    - nginx